### ISSUE TITLE
Libmemcached from FastoNoSQL

### ISSUE THREAD

**Issue by topilski** [awesomized/libmemcached#123]
Hello, thank you for your work, we also have fork from libmemcached, may be some our changes will be useful for your implementation: https://github.com/fastogt/libmemcached

**Comment by m6w6** [comment]
Hi! Thanks for the heads up!

I browsed through your commits and I think that all of them are already fixed in libmemcached-awesome, except the TTL API change of the `memcached_dump` callback, which would need a new major version (i.e. 2.0) including a SOVERSION bump.

For more general information, please have look the the [README](https://github.com/awesomized/libmemcached/blob/v1.x/README.md).
If you want to know what was done to bring libmemcached back to live have a look at the [v1.1 ChangeLog](https://awesomized.github.io/libmemcached/ChangeLog-1.1.html).
